name: ffi_objc_main_thread
description: Trying to run dart code in the main thread
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  args: ^2.4.0
  ffi: ^2.0.1
  path: ^1.8.3

dev_dependencies:
  ffigen: ^7.2.9
  lints: ^2.0.0

executables:
  compile: compile
  generate: generate